Fix for attribute operations resulting in string operations
loominc/json0-ot-diff pull request #1
Opened 2017-07-23 13:04 UTC by manufacturist

This PR contains a fix for attribute operations (object - oi and od) being converted to string operations within the 'diff' function (index.js, line 47).

This is not an issue if the target attribute does not exist or is being removed, however when changing an attribute value, string operations will be generated (i.e contenteditable='true' to contenteditable='false').

Added a new test scenario and added expected ops for the second existing test. The tests run properly with the 'No errors!' message showing at the end.

Notes:
1. Line 78 in index.js - The condition 'treatAsStringOp === undefined' is required for the unicode test scenarios
2. Line 209 in tests.js - The assertion is done in an ordered manner

2017-07-24 14:43 UTC, tberman requested changes
I guess I don't get what we are trying to do here. Is the issue that the text0 diff takes more space than the simple replacement diff?

2017-07-24 14:43 UTC, tberman commented on tests.js
> +// Expected ops for each test
You should add this to the main test runner, no need for another harness

2017-07-24 16:21 UTC, manufacturist commented
Since the code already has support for 'od' and 'oi' operations thanks to the json0 OT, why should the text0 OT handle them?

Using object delete and insert operations is slightly faster (fewer operations are needed to obtain them / apply them) and as you mentioned, the required space to store them is smaller.

Also, why use the text0 OT only when modifying the value of an attribute and not when creating or deleting it? This PR aims to make things a little more consistent.

2017-07-24 16:26 UTC, tberman commented
So text0 is only really useful for diffing strings not for creating or deleting them (as you have rightly pointed out). That is why we use it only when both operands are strings. 

As far as it being simpler, it can definitely be simpler but it can also be more complex. For example imagine a case where the string is 300 characters and you are just inserting 3 characters at a specific index?

I think there is an interesting patch here that looks at the edit distance between the two strings and use that to determine if you should use oi/od or text0 for a specific string diff. 

Would you be interested in writing that?

2017-07-24 20:31 UTC, manufacturist commented
I would be interested in writing such a patch (just for the fun of it), however I am currently busy for the next couple of weeks.

For my personal use case, the maximum length of an attribute value is usually less than ~10 characters and these operations don't appear that often. Using od / oi ops is the optimal use case for me (that's why I didn't think about such scenarios).

The patch should check which op would occupy more storage space, right? Or should the code complexity / performance be taken into consideration as well when deciding which op to use?

2017-07-25 00:47 UTC, tberman commented
I would probably focus on computational complexity, which is likely # of edits as a ratio to the string length. I would look at edit distance for sure. And probably make it tunable?

2022-02-15 07:54 UTC, closed without merging